version: '3.8'

services:
  backend:
    env_file: .env.local
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    restart: always
    volumes:
      - ./backend:/app
    tty: true
    stdin_open: true
